# Generated by Django 5.0.1 on 2024-04-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_studentinfo_address_studentinfo_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='blood_group',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='contact_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='father_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='joining_year',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mother_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='room_no',
            field=models.IntegerField(),
        ),
    ]
