# Generated by Django 5.0.1 on 2024-04-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_wardeninfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardeninfo',
            name='isfemale',
        ),
        migrations.RemoveField(
            model_name='wardeninfo',
            name='ismale',
        ),
        migrations.AddField(
            model_name='wardeninfo',
            name='gender',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='wardeninfo',
            name='blood_group',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='wardeninfo',
            name='contact_number',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='wardeninfo',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='wardeninfo',
            name='joining_year',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='wardeninfo',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='wardeninfo',
            name='room_no',
            field=models.IntegerField(default=None),
        ),
    ]
