# Generated by Django 5.0.1 on 2024-04-02 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_alter_wardeninfo_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_type', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=5)),
                ('vacant', models.BooleanField(default=False)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
                ('member1_roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member1_rooms', to='hostel.studentinfo')),
                ('member2_roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2_rooms', to='hostel.studentinfo')),
            ],
        ),
    ]
