# Generated by Django 5.0.1 on 2024-04-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_hostel_filled_seats_count_alter_hostel_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='filled_seats_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
